title: Simon Stone # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Simon, and I am a recent graduate with a degree in Applied Physics looking to work in tech. My interests include renewable energy, biotech, electronics, optics, photonics, telecommunications, software, and everything in-between! My relevant coursework includes differential equations, linear algebra, applied electromagnetic physics, RF & microwave physics, quantum mechanics, semiconductor physics, computational electromagnetics, and Optics & Quantum Electronics, among others. I have an extensive background in experimental and computational research. I am proficient in Excel, Python, and MATLAB. 
  <a href="https://www.linkedin.com/in/simon-stone-4aa032164/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
