title: Simon Stone # your name (or website title) here
logo: "/images/IMG_7210.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Simon, and I am a recent graduate with a degree in Applied Physics looking to exercise my skills in the development of meaninful technology.
  <br><br>
  My interests include renewable energy, biotech, electronics, optics, photonics, telecommunications, software, and everything in-between! 
  <br><br>
  <a href="https://www.linkedin.com/in/simon-stone-4aa032164/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/slstone24">View My GitHub Profile</a> 
  <br><br>
theme: jekyll-theme-minimal

